info:
  project_name: project_1
  model_name: resnet50
  model_task: classification
  data_root_dir: /home/sdk/Work/est_projects/03-cv/est_wassup_03/features # est_wassup_03/features
train:
  epochs: 20
  lr_scheduler: coslr # available lr scheduler = ['coslr', 'steplr'] # None if lr_scheduler is not wanted
  lr_scheduler_params:
    # step_size: 2 # steplr params
    # gamma: 0.1 # steplr params
    # last_epoch: -1 # steplr params
    T_max: 10
    eta_min: 0.000001
  batch: 16
  imgsz: 224
  device: 0 # int for single gpu or tuple for multiple gpu usage. e.g. (0, 1, 2, 3) # if gpu is not available, use cpu or mps
  optimizer: adamw # available optimizer = ['sgd', 'adam', 'adamw']
  optimizer_params:
    lr: 0.001
    weight_decay: 0.01  
  pretrained: # pretrained weight if wanted
  seed: 2024
  dropout: 0.3 # 0.0 for no dropout
  conf: # object detection confidence threshold
  loss_fn: cross_entropy # ['cross_entropy']
infer:
  src_dir: /home/sdk/Work/est_projects/03-cv/est_wassup_03/features
  pretrained: /home/sdk/Work/est_projects/03-cv/est_wassup_03/shape_predictor_68_face_landmarks.dat
  infer_type: "dlib"